
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    database:
      driverClassName: org.hibernate.dialect.MYSQL5InnoDBDialect
    hibernate:
      ddl-auto: update  
server:
  port: 8089
